spring:
  application:
    name: producer

  Kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

#logging:
#  level:
#    org.apache.kafka: INFO
#    org.springframework.kafka: INFO
#    com.hongleap.producer: DEBUG
